# PRODUCTION DOCKERFILE

# --- Build Stage

FROM golang:1.17 AS build
WORKDIR /mnt
# copy source
COPY ./src .
# build (this will auto install deps from go.mod)
RUN mkdir -p dist
RUN CGO_ENABLED=0 GOOS=linux go build -a -o dist/app .

# --- Run Stage

FROM alpine:latest  
RUN apk --no-cache add ca-certificates

# copy binary from build stage
WORKDIR /root/
COPY --from=build /mnt/dist/ ./

# when the container is started, run the binary
CMD ["./app"]

